LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= su.c

LOCAL_MODULE:= su

LOCAL_FORCE_STATIC_EXECUTABLE := true

LOCAL_STATIC_LIBRARIES := libc

LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)

ifeq ($(ENABLE_SU_INSTALL),true)
LOCAL_MODULE_TAGS := optional
else
LOCAL_MODULE_TAGS := debug
endif

include $(BUILD_EXECUTABLE)
