#!/system/bin/sh
#
# Script to start "ttm" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/ttm.jar
exec app_process $base/bin com.tcl.commands.ttm.Ttm "$@"

