package com.mediatek.tvcommon;

import com.mediatek.tv.common.ConfigType;

public enum IntegerOption {

	CFG_AD_VOLUME(ConfigType.CFG_AD_VOLUME, 20, 0, 100), CFG_VIDEO_MSI(
		    ConfigType.CFG_VIDEO_MSI, 0, 0, 1), CFG_FBM_MODE(
			ConfigType.CFG_FBM_MODE, 1, 1, 2), CFG_TTX_DIGITAL_LANG(
			ConfigType.CFG_TTX_DIGITAL_LANG, 0, 0, 40), CFG_TTX_DECODE_PAGE(
			ConfigType.CFG_TTX_DECODE_PAGE, 0, 0, 9), CFG_TTX_PRESENTATION_LVL(
			ConfigType.CFG_TTX_PRESENTATION_LVL, 0, 0, 1), CFG_3D_DISTANCE(
			ConfigType.CFG_3D_DISTANCE, 10, 2, 18), CFG_IMG_SFTY(
			ConfigType.CFG_IMG_SFTY, ConfigType.CFG_VID_3D_IMG_STFY_OFF,
			ConfigType.CFG_VID_3D_IMG_STFY_OFF,
			ConfigType.CFG_VID_3D_IMG_STFY_HIGH),
			CFG_EARLY_PLAY(ConfigType.CFG_EARLY_PLAY,
                ConfigType.EARLY_PLAY_DISENABLED,
                ConfigType.EARLY_PLAY_DISENABLED,
                ConfigType.EARLY_PLAY_ENABLED),

	CFG_3D_DEPTH_OF_FIELD(ConfigType.CFG_3D_DEPTH_OF_FIELD, 16, 0, 32), CFG_3D_LR_SWITCH(
			ConfigType.CFG_3D_LR_SWITCH, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_3D_MODE(
			ConfigType.CFG_3D_MODE, ConfigType.CFG_3D_MODE_OFF,
			ConfigType.CFG_3D_MODE_OFF, ConfigType.CFG_3D_MODE_CHK_BOARD), CFG_3D_NAV_AUTO(
			ConfigType.CFG_3D_NAV_AUTO,
			ConfigType.CFG_VID_3D_NAV_AUTO_CHG_SEMI_AUTO,
			ConfigType.CFG_VID_3D_NAV_AUTO_CHG_MANUAL,
			ConfigType.CFG_VID_3D_NAV_AUTO_CHG_AUTO), CFG_3D_TO_2D(
			ConfigType.CFG_3D_TO_2D, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_3D_VIEW_POINT(
			ConfigType.CFG_3D_VIEW_POINT, 0, 0, 32), CFG_ASPECT_RATIO(
			ConfigType.CFG_ASPECT_RATIO, ConfigType.SCREEN_MODE_NORMAL,
			ConfigType.SCREEN_MODE_NORMAL, ConfigType.SCREEN_MODE_DOT_BY_DOT), CFG_AUDIO_CURVE_20(
			ConfigType.CFG_AUDIO_CURVE_20, 0, 0, 100), CFG_AUDIO_CURVE_80(
			ConfigType.CFG_AUDIO_CURVE_80, 0, 0, 100), CFG_AUDIO_CURVE_MAX(
			ConfigType.CFG_AUDIO_CURVE_MAX, 0, 0, 100), CFG_AUDIO_CURVE_MID(
			ConfigType.CFG_AUDIO_CURVE_MID, 0, 0, 100), CFG_AUDIO_CURVE_MIN(
			ConfigType.CFG_AUDIO_CURVE_MIN, 0, 0, 100), CFG_AUDIO_DELAY(
			ConfigType.CFG_AUDIO_DELAY, 0, 0, 30), CFG_AUDIO_MODE(
			ConfigType.CFG_AUDIO_MODE, ConfigType.AUDIO_MODE_USER,
			ConfigType.AUDIO_MODE_USER, ConfigType.AUDIO_MODE_LIVE1), CFG_AVCMODE(
			ConfigType.CFG_AVCMODE, ConfigType.COMMON_ON,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_BACKLIGHT(
			ConfigType.CFG_BACKLIGHT, 50, 0, 100), CFG_BALANCE(
			ConfigType.CFG_BALANCE, 0, -50, 50), CFG_BLUE_SCREEN(
			ConfigType.CFG_BLUE_SCREEN, ConfigType.COMMON_ON,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_BLUE_STRETCH(
			ConfigType.CFG_BLUE_STRETCH, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_BRIGHTNESS(
			ConfigType.CFG_BRIGHTNESS, 50, 0, 100), CFG_CLOCK(
			ConfigType.CFG_CLOCK, 0, 0, 255), CFG_COLOR_GAIN_B(
			ConfigType.CFG_COLOR_GAIN_B, 0, -20, 20), CFG_COLOR_GAIN_G(
			ConfigType.CFG_COLOR_GAIN_G, 0, -20, 20), CFG_COLOR_GAIN_R(
			ConfigType.CFG_COLOR_GAIN_R, 0, -20, 20), CFG_COLOR_OFFSET_B(
			ConfigType.CFG_COLOR_OFFSET_B, 0, -20, 20), CFG_COLOR_OFFSET_G(
			ConfigType.CFG_COLOR_OFFSET_G, 0, -20, 20), CFG_COLOR_OFFSET_R(
			ConfigType.CFG_COLOR_OFFSET_R, 0, -20, 20), CFG_CONTRAST(
			ConfigType.CFG_CONTRAST, 50, 0, 100), CFG_CTI(ConfigType.CFG_CTI,
			ConfigType.VID_CTI_MEDIUM, ConfigType.VID_CTI_OFF,
			ConfigType.VID_CTI_STRONG), CFG_EQUALIZE(ConfigType.CFG_EQUALIZE,
			ConfigType.CFG_AUD_SE_EQ_OFF, ConfigType.CFG_AUD_SE_EQ_OFF,
			ConfigType.CFG_AUD_SE_EQ_SOFT),

	CFG_EQ_BAND_1(ConfigType.CFG_EQ_BAND_1, 0, -60, 60), CFG_EQ_BAND_2(
			ConfigType.CFG_EQ_BAND_2, 0, -60, 60), CFG_EQ_BAND_3(
			ConfigType.CFG_EQ_BAND_3, 0, -60, 60), CFG_EQ_BAND_4(
			ConfigType.CFG_EQ_BAND_4, 0, -60, 60), CFG_EQ_BAND_5(
			ConfigType.CFG_EQ_BAND_5, 0, -60, 60), CFG_EQ_BAND_6(
			ConfigType.CFG_EQ_BAND_6, 0, -60, 60), CFG_EQ_BAND_7(
			ConfigType.CFG_EQ_BAND_7, 0, -60, 60),

	CFG_EQUALIZE_10KHZ(ConfigType.CFG_EQUALIZE_10KHZ, 0, -60, 60), CFG_EQUALIZE_120HZ(
			ConfigType.CFG_EQUALIZE_120HZ, 0, -60, 60), CFG_EQUALIZE_1500HZ(
			ConfigType.CFG_EQUALIZE_1500HZ, 0, -60, 60), CFG_EQUALIZE_500HZ(
			ConfigType.CFG_EQUALIZE_500HZ, 0, -60, 60), CFG_EQUALIZE_5KHZ(
			ConfigType.CFG_EQUALIZE_5KHZ, 0, -60, 60), CFG_FAC_BL_BRI(
			ConfigType.CFG_FAC_BL_BRI, 0, 0, 100), CFG_FAC_BL_OPT_1(
			ConfigType.CFG_FAC_BL_OPT_1, 0, 0, 100), CFG_FAC_BL_OPT_2(
			ConfigType.CFG_FAC_BL_OPT_2, 0, 0, 100), CFG_FAC_BL_OPT_3(
			ConfigType.CFG_FAC_BL_OPT_3, 0, 0, 100), CFG_FAC_BL_OPT_4(
			ConfigType.CFG_FAC_BL_OPT_4, 0, 0, 100), CFG_FAC_BL_OPT_5(
			ConfigType.CFG_FAC_BL_OPT_5, 0, 0, 100), CFG_FAC_BL_OPT_6(
			ConfigType.CFG_FAC_BL_OPT_6, 0, 0, 100), CFG_FAC_BL_SOFT(
			ConfigType.CFG_FAC_BL_SOFT, 0, 0, 100), CFG_FAC_BL_USER(
			ConfigType.CFG_FAC_BL_USER, 0, 0, 100), CFG_FLESH_TONE(
			ConfigType.CFG_FLESH_TONE, ConfigType.VID_FLESH_TONE_MIDDLE,
			ConfigType.VID_FLESH_TONE_OFF, ConfigType.VID_FLESH_TONE_STRONG), CFG_GAMMA(
			ConfigType.CFG_GAMMA, ConfigType.VID_GAMMA_MIDDLE,
			ConfigType.VID_GAMMA_DARK, ConfigType.VID_GAMMA_BRIGHT), CFG_H_POSITION(
			ConfigType.CFG_H_POSITION, 0, -16, 16), CFG_H_SIZE(
			ConfigType.CFG_H_SIZE, 0, -5, 5), CFG_HUE(ConfigType.CFG_HUE, 0,
			-50, 50), CFG_LUMA(ConfigType.CFG_LUMA, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.VID_LUMA_STRONG), CFG_MAGIC_AV_SYSTEM(
			ConfigType.CFG_MAGIC_AV_SYSTEM, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_MEMC(
			ConfigType.CFG_MEMC, ConfigType.COMMON_OFF, ConfigType.COMMON_OFF,
			ConfigType.COMMON_ON), CFG_MEMC_DEMO(ConfigType.CFG_MEMC_DEMO,
			ConfigType.COMMON_OFF, ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_NR(
			ConfigType.CFG_NR, ConfigType.VID_DNR_MEDIUM,
			ConfigType.VID_DNR_OFF, ConfigType.VID_DNR_AUTO),

	CFG_3DNR(ConfigType.CFG_3DNR, ConfigType.VID_DNR_MEDIUM,
			ConfigType.VID_DNR_OFF, ConfigType.VID_DNR_AUTO),

	CFG_PHASE(ConfigType.CFG_PHASE, 12, 0, 31), CFG_YPBPR_PHASE(
			ConfigType.CFG_YPBPR_PHASE, 12, 0, 31),

	CFG_PICTURE_MODE(ConfigType.CFG_PICTURE_MODE, ConfigType.PICTURE_MODE_USER,
			ConfigType.PICTURE_MODE_USER, ConfigType.PICTURE_MODE_HI_BRIGHT), CFG_POWER_SAVE(
			ConfigType.CFG_POWER_SAVE, ConfigType.POWER_SAVE_MODE_USER,
			ConfigType.POWER_SAVE_MODE_USER, ConfigType.POWER_SAVE_MODE_DYNAMIC), CFG_SATURATION(
			ConfigType.CFG_SATURATION, 50, 0, 100), CFG_SCREEN_MODE(
			ConfigType.CFG_SCREEN_MODE, ConfigType.SCREEN_MODE_NORMAL,
			ConfigType.SCREEN_MODE_UNKNOWN,
			ConfigType.SCREEN_MODE_NLZ_CUSTOM_DEF_3),

	CFG_SHARPNESS(ConfigType.CFG_SHARPNESS, 4, 0, 20), CFG_SOUND_FIELD_LOCATE_MODE(
			ConfigType.CFG_SOUND_FIELD_LOCATE_MODE,
			ConfigType.SOUND_FIELD_LOCATE_MODE_DESK,
			ConfigType.SOUND_FIELD_LOCATE_MODE_WALL,
			ConfigType.SOUND_FIELD_LOCATE_MODE_DESK), CFG_SPDIF_MODE(
			ConfigType.CFG_SPDIF_MODE, ConfigType.SPDIF_MODE_FMT_PCM24,
			ConfigType.SPDIF_MODE_FMT_OFF, ConfigType.SPDIF_MODE_FMT_PCM24), CFG_SPEAKER_MODE(
			ConfigType.CFG_SPEAKER_MODE, ConfigType.SPEAKER_MODE_INTERNAL,
			ConfigType.SPEAKER_MODE_INTERNAL, ConfigType.SPEAKER_MODE_EXTERNAL), CFG_SRS_MODE(
			ConfigType.CFG_SRS_MODE, ConfigType.COMMON_ON,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_TEMPERATURE(
			ConfigType.CFG_TEMPERATURE, ConfigType.VID_CLR_TEMP_USER,
			ConfigType.VID_CLR_TEMP_USER, ConfigType.VID_CLR_TEMP_WARM), CFG_V_POSITION(
			ConfigType.CFG_V_POSITION, 0, -16, 16), CFG_V_SIZE(
			ConfigType.CFG_V_SIZE, 0, -5, 5), CFG_VIDEO_CURVE_BRI_MAX(
			ConfigType.CFG_VIDEO_CURVE_BRI_MAX, 0, 0, 255), CFG_VIDEO_CURVE_BRI_MID(
			ConfigType.CFG_VIDEO_CURVE_BRI_MID, 0, 0, 255), CFG_VIDEO_CURVE_BRI_MIN(
			ConfigType.CFG_VIDEO_CURVE_BRI_MIN, 0, 0, 255), CFG_VIDEO_CURVE_CNT_MAX(
			ConfigType.CFG_VIDEO_CURVE_CNT_MAX, 0, 0, 255), CFG_VIDEO_CURVE_CNT_MID(
			ConfigType.CFG_VIDEO_CURVE_CNT_MID, 0, 0, 255), CFG_VIDEO_CURVE_CNT_MIN(
			ConfigType.CFG_VIDEO_CURVE_CNT_MIN, 0, 0, 255), CFG_VIDEO_CURVE_HUE_MAX(
			ConfigType.CFG_VIDEO_CURVE_HUE_MAX, 0, 0, 255), CFG_VIDEO_CURVE_HUE_MID(
			ConfigType.CFG_VIDEO_CURVE_HUE_MID, 0, 0, 255), CFG_VIDEO_CURVE_HUE_MIN(
			ConfigType.CFG_VIDEO_CURVE_HUE_MIN, 0, 0, 255), CFG_VIDEO_CURVE_SHP_MAX(
			ConfigType.CFG_VIDEO_CURVE_SHP_MAX, 0, 0, 255), CFG_VIDEO_CURVE_SHP_MID(
			ConfigType.CFG_VIDEO_CURVE_SHP_MID, 0, 0, 255), CFG_VIDEO_CURVE_SHP_MIN(
			ConfigType.CFG_VIDEO_CURVE_SHP_MIN, 0, 0, 255), CFG_VIDEO_CURVE_VID_MAX(
			ConfigType.CFG_VIDEO_CURVE_VID_MAX, 0, 0, 255), CFG_VIDEO_CURVE_VID_MID(
			ConfigType.CFG_VIDEO_CURVE_VID_MID, 0, 0, 255), CFG_VIDEO_CURVE_VID_MIN(
			ConfigType.CFG_VIDEO_CURVE_VID_MIN, 0, 0, 255), CFG_VOLUME(
			ConfigType.CFG_VOLUME, 20, 0, 100), CFG_AUD_AD_HDPHONE(
			ConfigType.CFG_AUD_AD_HDPHONE, ConfigType.COMMON_ON,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_AUD_AD_SPEAKER(
			ConfigType.CFG_AUD_AD_SPEAKER, ConfigType.COMMON_ON,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_WHITE_PEAK_LMT(
			ConfigType.CFG_WHITE_PEAK_LMT, ConfigType.COMMON_ON,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_WME_MODE(
			ConfigType.CFG_WME_MODE, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_GAME_MODE(
			ConfigType.CFG_GAME_MODE, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON),

	CFG_SPDIF_DELAY(ConfigType.CFG_SPDIF_DELAY, 0, 0, 25), CFG_AUD_CHANNEL(
			ConfigType.CFG_AUD_CHANNEL, 0, 0, 2),

	CFG_SPEAKER(ConfigType.CFG_SPEAKER, ConfigType.AUDIO_SPEAKER_ON,
			ConfigType.AUDIO_SPEAKER_OFF, ConfigType.AUDIO_SPEAKER_ON), CFG_AUD_BASS(
			ConfigType.CFG_AUD_BASS, 50, 0, 100), CFG_DOLBY_BANNER(
			ConfigType.CFG_DOLBY_BANNER, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_DOLBY_CMPR_MODE(
			ConfigType.CFG_DOLBY_CMPR_MODE, ConfigType.AUD_CMPSS_MDOE_LINE,
			ConfigType.AUD_CMPSS_MDOE_LINE, ConfigType.AUD_CMPSS_MDOE_RF),

	CFG_DOLBY_CMPR_FACTOR(ConfigType.CFG_DOLBY_CMPR_FACTOR,
			ConfigType.AUD_DOLBY_DRC_FULL, ConfigType.AUD_DOLBY_DRC_OFF,
			ConfigType.AUD_DOLBY_DRC_FULL),

	CFG_AUDIO_TYPE(ConfigType.CFG_AUDIO_TYPE, ConfigType.AUDIO_TYPE_0,
			ConfigType.AUDIO_TYPE_0, ConfigType.AUDIO_TYPE_3),

	CFG_VGA_POS_H(ConfigType.CFG_VGA_POS_H, 0, 0, 100),

	CFG_VGA_POS_V(ConfigType.CFG_VGA_POS_V, 0, 0, 100),

	CFG_VGA_PHASE(ConfigType.CFG_VGA_PHASE, 0, 0, 31), CFG_VGA_CLOCK(
			ConfigType.CFG_VGA_CLOCK, 0, 0, 255),

	CFG_MPEG_NR(ConfigType.CFG_MPEG_NR, ConfigType.VID_MPEG_NR_LOW,
			ConfigType.VID_MPEG_NR_OFF, ConfigType.VID_MPEG_NR_STRONG),

	CFG_DI_FILM_MODE(ConfigType.CFG_DI_FILM_MODE,
			ConfigType.VID_DI_FILE_MODE_ACTION_PIC,
			ConfigType.VID_DI_FILM_MODE_OFF,
			ConfigType.VID_DI_FILE_MODE_ACTION_PIC),

	CFG_VGAMODE(ConfigType.CFG_VGAMODE,
			ConfigType.VID_VGA_MODE_COLORSPACE_FORCE_RGB,
			ConfigType.VID_VGA_MODE_COLORSPACE_AUTO,
			ConfigType.VID_VGA_MODE_COLORSPACE_FORCE_YCBCR), CFG_HDMI_MODE(
			ConfigType.CFG_HDMI_MODE, ConfigType.HDMI_MODE_GRAPHIC,
			ConfigType.HDMI_MODE_AUTO, ConfigType.HDMI_MODE_VIDEO),

	CFG_DI_MA(ConfigType.CFG_DI_MA, ConfigType.VID_DI_MA_ACTION_PIC,
			ConfigType.VID_DI_MA_SLOW_PIC, ConfigType.VID_DI_MA_ACTION_PIC),

	CFG_DI_EDGE(ConfigType.CFG_DI_EDGE, ConfigType.VID_DI_EDGE_WEAK,
			ConfigType.VID_DI_EDGE_WEAK, ConfigType.VID_DI_EDGE_STRONG),

	CFG_WCG(ConfigType.CFG_WCG, ConfigType.COMMON_ON, ConfigType.COMMON_OFF,
			ConfigType.COMMON_ON),

	CFG_VIDEO_FLIP(ConfigType.CFG_VIDEO_FLIP, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_VIDEO_MIRROR(
			ConfigType.CFG_VIDEO_MIRROR, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_CH_FRZ_CHG(
			ConfigType.CFG_CH_FRZ_CHG, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_AUD_TREBLE(
			ConfigType.CFG_AUD_TREBLE, 50, 0, 100), CFG_AUD_MTS(
			ConfigType.CFG_AUD_MTS, ConfigType.AUD_MTS_STEREO,
			ConfigType.AUDIO_MTS_UNKNOW, ConfigType.AUD_MTS_FM_STEREO), CFG_WAKE_UP_REASON(
			ConfigType.CFG_WAKE_UP_REASON, ConfigType.WAKE_UP_REASON_UNKNOWN,
			ConfigType.WAKE_UP_REASON_UNKNOWN,
			ConfigType.WAKE_UP_REASON_CUSTOM_4),

	CFG_GET_SCREEN_MODE_NUM(ConfigType.CFG_GET_SCREEN_MODE_NUM, 0, 0, 18), CFG_GET_NEXT_SCREEN_MODE(
			ConfigType.CFG_GET_NEXT_SCREEN_MODE, 0, 0, 18), CFG_GET_PREV_SCREEN_MODE(
			ConfigType.CFG_GET_PREV_SCREEN_MODE, 0, 0, 18), CFG_GET_THIS_SCREEN_MODE(
			ConfigType.CFG_GET_THIS_SCREEN_MODE, 0, 0, 18), CFG_GET_FIRST_SCREEN_MODE(
			ConfigType.CFG_GET_FIRST_SCREEN_MODE, 0, 0, 18), CFG_GET_LAST_SCREEN_MODE(
			ConfigType.CFG_GET_LAST_SCREEN_MODE, 0, 0, 18),

	CFG_VOLUME_FRONT_LEFT(ConfigType.CFG_VOLUME_FRONT_LEFT, 20, 0, 100), CFG_VOLUME_FRONT_RIGHT(
			ConfigType.CFG_VOLUME_FRONT_RIGHT, 20, 0, 100), CFG_VOLUME_REAR_LEFT(
			ConfigType.CFG_VOLUME_REAR_LEFT, 20, 0, 100), CFG_VOLUME_REAR_RIGHT(
			ConfigType.CFG_VOLUME_REAR_RIGHT, 20, 0, 100), CFG_VOLUME_CENTER(
			ConfigType.CFG_VOLUME_CENTER, 20, 0, 100), CFG_VOLUME_SUB_WOOFER(
			ConfigType.CFG_VOLUME_SUB_WOOFER, 20, 0, 100),

	MENU_AUD_LANG(ConfigType.MENU_AUD_LANG,
			ConfigType.AUD_LANG_STREAMLANG_ENGLISH,
			ConfigType.AUD_LANG_STREAMLANG_ENGLISH,
			ConfigType.AUD_LANG_STREAMLANG_ZHONGGUO), MENU_AUD_LANG_2ND(
			ConfigType.MENU_AUD_LANG_2ND,
			ConfigType.AUD_LANG_STREAMLANG_ENGLISH,
			ConfigType.AUD_LANG_STREAMLANG_ENGLISH,
			ConfigType.AUD_LANG_STREAMLANG_ZHONGGUO), POWER_ON_MUSIC(
			ConfigType.POWER_ON_MUSIC, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), POWER_OFF_MUSIC(
			ConfigType.POWER_OFF_MUSIC, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), CFG_DPMS(
			ConfigType.CFG_DPMS, ConfigType.COMMON_ON, ConfigType.COMMON_OFF,
			ConfigType.COMMON_ON), CFG_WAKEUP_VGA_SETUP(
			ConfigType.CFG_WAKEUP_VGA_SETUP,
			ConfigType.WAKE_UP_SETUP_VGA_INVALIDE,
			ConfigType.WAKE_UP_SETUP_VGA_INVALIDE,
			ConfigType.WAKE_UP_SETUP_VGA_VALIDE), CFG_POWER_ON_TIMER(
			ConfigType.CFG_POWER_ON_TIMER, 0, 0, 86400), CFG_TIME_SYNC(
			ConfigType.CFG_TIME_SYNC, ConfigType.TIME_SYNC_MODE_AUTO,
			ConfigType.TIME_SYNC_MODE_AUTO, ConfigType.TIME_SYNC_MODE_MANUAL),

	CFG_AUD_DMIX(ConfigType.CFG_AUD_DMIX, ConfigType.AUD_DOWNMIX_MODE_DUAL_OFF,
			ConfigType.AUD_DOWNMIX_MODE_OFF,
			ConfigType.AUD_DOWNMIX_MODE_DUAL_OFF), CFG_AUDIO_ONLY(
			ConfigType.CFG_AUDIO_ONLY, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON),

	CFG_MJC_FCT(ConfigType.CFG_MJC_FCT, ConfigType.CFG_MJC_OFF,
			ConfigType.CFG_MJC_OFF, ConfigType.CFG_MJC_ON), CFG_MJC_MODE(
			ConfigType.CFG_MJC_MODE, ConfigType.CFG_MJC_MODE_NONE,
			ConfigType.CFG_MJC_MODE_0, ConfigType.CFG_MJC_MODE_NONE),

	CFG_MJC_EFFECT(ConfigType.CFG_MJC_EFFECT, ConfigType.CFG_MJC_EFFECT_OFF,
			ConfigType.CFG_MJC_EFFECT_OFF, ConfigType.CFG_MJC_EFFECT_HIGH), CFG_MJC_DEMO(
			ConfigType.CFG_MJC_DEMO, ConfigType.CFG_MJC_DEMO_OFF,
			ConfigType.CFG_MJC_DEMO_OFF, ConfigType.CFG_MJC_DEMO_LEFT), CFG_AUD_OUTDEV(
			ConfigType.CFG_AUD_OUTDEV, ConfigType.AUD_OUTDEV_SPEAKER,
			ConfigType.CFG_MJC_DEMO_OFF, ConfigType.AUD_OUTDEV_BLUETEETH), CFG_BS_SRC(
			ConfigType.CFG_BS_SRC, ConfigType.BS_SRC_CABLE,
			ConfigType.BS_SRC_AIR, ConfigType.BS_SRC_CABLE),

	CFG_TV_FOCUS_WIN(ConfigType.CFG_TV_FOCUS_WIN, ConfigType.TV_FOCUS_WIN_MAIN,
			ConfigType.TV_FOCUS_WIN_MAIN, ConfigType.TV_FOCUS_WIN_SUB), CFG_SHOW_DEFAULT_SCREEN_MODE(
			ConfigType.CFG_SHOW_DEFAULT_SCREEN_MODE, ConfigType.TV_WIN_MAIN,
			ConfigType.TV_WIN_MAIN, ConfigType.TV_WIN_SUB), CFG_TV_MODE(
			ConfigType.CFG_TV_MODE, ConfigType.TV_MODE_NORMAL,
			ConfigType.TV_MODE_NORMAL, ConfigType.TV_MODE_POP), CFG_VIDEO_PQ_DEMO(
			ConfigType.CFG_VIDEO_PQ_DEMO, ConfigType.VID_PQ_DEMO_OFF,
			ConfigType.VID_PQ_DEMO_OFF, ConfigType.VID_PQ_DEMO_ON),

	CEC_CEC_FUNC(ConfigType.CEC_CEC_FUNC, ConfigType.CEC_FUNC_OFF,
			ConfigType.CEC_FUNC_OFF, ConfigType.CEC_FUNC_ON), 
	CEC_AUTO_OFF(ConfigType.CEC_AUTO_OFF, ConfigType.AUTO_OFF_DISENABLED,
			ConfigType.AUTO_OFF_DISENABLED, ConfigType.AUTO_OFF_ENABLED), 
	CEC_AUTO_ON(ConfigType.CEC_AUTO_ON, ConfigType.AUTO_ON_DISENABLED,
			ConfigType.AUTO_ON_DISENABLED, ConfigType.AUTO_ON_ENABLED), 
	CEC_SAC_FUNC(ConfigType.CEC_SAC_FUNC, ConfigType.SAC_FUNC_OFF,
			ConfigType.SAC_FUNC_OFF, ConfigType.SAC_FUNC_ON), 
	CFG_TUNNER_MODE_CHG(ConfigType.CFG_TUNNER_MODE_CHG, ConfigType.COMMON_OFF, 
	        ConfigType.COMMON_OFF, ConfigType.COMMON_ON), 
	CFG_PRE_SELECT_RESET(ConfigType.CFG_PRE_SELECT_RESET, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON), 
	CFG_INPUT_SOURCE_BLOCK(ConfigType.CFG_INPUT_SOURCE_BLOCK, ConfigType.COMMON_OFF,
			ConfigType.COMMON_OFF, ConfigType.COMMON_ON);

	private String name;
	private int defaultVal;
	private int min;
	private int max;

	private IntegerOption(String name, int defaultVal, int min, int max) {
		this.name = name;
		this.defaultVal = defaultVal;
		this.min = min;
		this.max = max;
	}

	public String getName() {
		return name;
	}

	public int getDefaultVal() {
		return defaultVal;
	}

	public int getMin() {
		return min;
	}

	public int getMax() {
		return max;
	}

	static public IntegerOption contain(String name) {
		for (IntegerOption option : IntegerOption.values()) {
			if (name.equals(option.name)) {
				return option;
			}
		}
		return null;
	}
}
